### ISSUE TITLE
Cannot import it from ESM

### ISSUE THREAD

**Issue by dword-design** [stagas/puppeteer-pretty-console#1]
Looks like it is currently not possible to import this lib from ESM because the `.js` extensions are missing in the build files. Also applies to all dependent libraries.

**Comment by stagas** [comment]
Yes that's unfortunate, which tooling do you use that requires .js extensions? It's working with Node/Typescript and should work with esbuild and swc as I'm using those in my projects.

**Comment by dword-design** [comment]
Just native ESM. So e.g. with `type: module` in `package.json` or `.mjs` extension. As far as I know it requires an extension when importing files.

**Comment by stagas** [comment]
Yeah you're right. I never noticed since I use commonjs under node, the ESM build is for esbuild/browser things. No clue what to do, I guess it's a problem with node.

**Comment by stagas** [comment]
Feel free to fork/copy/clone/republish anything you need @dword-design .
